version: "3"

services: 
  elastic:
    image: elasticsearch:7.4.0
    ports:
      - 9200:9200
      - "9300:9300"
    networks: 
      piax:  
    environment:
      discovery.type: single-node 
#    container_name: elasticsearch

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.14
    depends_on:
      - elastic
    ports: 
      - "14267:14267"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411" #(zipkin span, disabled by default)
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://piax:9200
                
#    image: jaegertracing/jaeger-agent:1.14
#    ports: 

networks: 
  piax:
   