version: "3"

services: 
  elastic:
    image: elasticsearch:7.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      some-network:  
    environment:
      discovery.type: single-node 
      xpack.ml.enabled: "false"

  collector:
    image: jaegertracing/jaeger-collector:1.14
    depends_on:
      - elastic
    ports: 
      - "14267:14267"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411" #(zipkin span, disabled by default)
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: "http://some-network:9200"

  agent:
    image: jaegertracing/jaeger-agent:1.14
    depends_on:
      - collector
    ports:
     - "6831:6831/udp"
     - "6832:6832/udp"
     - "5778:5778/tcp"
     - "5775:5775/udp"
    command:       
      ["--reporter.grpc.host-port=piax:14250"] # depend on /etc/hosts
  
  query:
    image: jaegertracing/jaeger-query
    ports:
      - "16686:16686"
      - "16687:16687"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://some-netowrk:9200

networks: 
  some-network:
